version: '3.2'

# ------------------------------------------  
# DEFINITION DES SERVICES
# ------------------------------------------ 
services:

  # ------- API --------------------------------------------
  demo-api:
    build: ./
    container_name: demo-api
    ports :
      - 80:80
    volumes:
      - ./app:/www/public
    depends_on:
      - demo-db
    networks:
      - api

  # ------- DATABASE ---------------------------------------
  demo-db:
    image: mariadb:10.2.11
    container_name: demo-db
    expose:
      - 3306
    volumes:
      - /srv/demodb:/var/lib/mysql:rw
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dbdemo
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    networks:
      - api
      - pma
      
  # ------- PHPMYADMIN --------------------------------------
  demo-pma:
    image: phpmyadmin/phpmyadmin
    container_name: demo-pma
    ports :
      - 8080:80
    depends_on:
      - demo-db
    environment:
      - PMA_HOST=demo-db
      - PMA_PORT=3306
    networks:
      - pma

# ------------------------------------------  
# DEFINITION DES RESEAUX
# ------------------------------------------ 
networks:
  api:
    driver: bridge
  pma:
    driver: bridge